### ISSUE TITLE
Error: Attempted relative import beyond top-level package???

### ISSUE THREAD

**Issue by MaxTran96** [chaojie/ComfyUI-I2VGEN-XL#5]
ERROR:root:Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-I2VGEN-XL/nodes.py", line 32, in load_checkpoint
    pipe = pipeline(task=task, model=model, model_revision=model_revision, device=device)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 134, in pipeline
    register_modelhub_repo(model, cfg.get('allow_remote', False))
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/plugins.py", line 455, in register_modelhub_repo
    import_module_from_model_dir(model_dir)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/plugins.py", line 400, in import_module_from_model_dir
    importlib.import_module(submodule)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/modelscope/modelscope_modules/i2vgen-xl/train_net.py", line 14, in <module>
    from tools import *
  File "/root/.cache/modelscope/modelscope_modules/i2vgen-xl/tools/__init__.py", line 1, in <module>
    from .modules import *
  File "/root/.cache/modelscope/modelscope_modules/i2vgen-xl/tools/modules/__init__.py", line 1, in <module>
    from .clip_embedder import FrozenOpenCLIPEmbedder
  File "/root/.cache/modelscope/modelscope_modules/i2vgen-xl/tools/modules/clip_embedder.py", line 9, in <module>
    from ...utils.registry_class import EMBEDDER
ImportError: attempted relative import beyond top-level packag

**Comment by MaxTran96** [comment]
Hi i fixed the above error using your README solution but im getting this error

```
RuntimeError: Failed to import modelscope.utils.hf_util because of the following error (look up to see its traceback):
cannot import name 'BitsAndBytesConfig' from 'transformers
```

**Comment by 973398769** [comment]
same error

**Comment by MaxTran96** [comment]
hi i'm getting this error. 
2024-01-30 22:41:24,997 - modelscope - INFO - Use user-specified model revision: v1.1.3
2024-01-30 22:41:26,721 - modelscope - WARNING - ('PIPELINES', 'image-to-video', 'i2v_gen_xl') not found in ast index file
usage: main.py [-h] [--cfg CFG_FILE] [--init_method INIT_METHOD] [--debug] ...
main.py: error: unrecognized arguments: --listen --port

why does it complaing about unrecognized arguments? when the argument is passed to start comfyui
python3 /workspace/ComfyUI/main.py --listen --port 3000 --preview-method auto

**Comment by MaxTran96** [comment]
@chaojie  can you take a look at this?

**Comment by PaulCollingwood** [comment]
it's not to delete the files, it's to remove their content! the files need to exist.
